#!/bin/bash
#
# repo maintenance script
#
branch=${1:-master}
case $branch in
  production)
    branch=master
    ;;
  *)
    branch=$branch
    ;;
esac
confdir=$(puppet --configprint confdir)
if [ -d "$confdir" ]; then
  cd $confdir && git reset --quiet --hard HEAD && git pull --quiet origin $branch
fi
